#!/usr/bin/env node

const { exec } = require('child_process');
const command = process.argv[2];
const argument = process.argv[3];

switch (command) {
    case 'commit':
        const commitMessage = argument || 'Kein Commit-Nachricht angegeben';
        exec(`git add . && git commit -m \